project:
  type: website
  output-dir: docs

website:
  title: "BCB520_DataViz"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Assignment 1"
        href: Assignment_1.qmd
      - text: "Assignment 2"
        href: Assignment_2.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Elsa7364

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
