project:
  type: website
  output-dir: docs

website:
  title: "BCB520 Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Elsa7364

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
