{
  "hash": "ba6598b280a5ada94c142d085332e6e1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data Visualization using Reddit Hyperlink Network\"\nSubtitle: \"Assignment 2 & 3\"\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    html-math-method: katex\n    code-copy: true\n    code-fold: true\n    code-tools: true\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n\n\n\n\nFor this assignment, I’m creating a data visualization using the **Reddit Hyperlink Network dataset** from **Stanford’s SNAP** ([source](https://snap.stanford.edu/data/soc-RedditHyperlinks.html)). This dataset tracks how different subreddits are connected through hyperlinks—basically, when one subreddit links to another in a post.\n\nI picked the second dataset to analyze subreddit interactions based on title mentions rather than mentions in in posts for simplicity. I'm using **Social Network Analysis (SNA)** to explore how communities interact and connect on Reddit. The goal is to visualize these relationships and see patterns in how subreddits reference each other!\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\n\nfile_path <- \"C:/Github repos/soc-redditHyperlinks-title.tsv\"\n\n# using read_tsv to read the data without needing to decompress it\nreddit_data <- read_tsv(file_path, comment = \"#\")\n\nhead(reddit_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  SOURCE_SUBREDDIT  TARGET_SUBREDDIT POST_ID TIMESTAMP           LINK_SENTIMENT\n  <chr>             <chr>            <chr>   <dttm>                       <dbl>\n1 rddtgaming        rddtrust         1u4pzzs 2013-12-31 16:39:18              1\n2 xboxone           battlefield_4    1u4tmfs 2013-12-31 17:59:11              1\n3 ps4               battlefield_4    1u4tmos 2013-12-31 17:59:40              1\n4 fitnesscirclejerk leangains        1u50xfs 2013-12-31 19:01:56              1\n5 fitnesscirclejerk lifeprotips      1u51nps 2013-12-31 21:02:28              1\n6 cancer            fuckcancer       1u5216s 2013-12-31 18:59:26              1\n# ℹ 1 more variable: PROPERTIES <chr>\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\nTo understand this, we’ll **turn the data into a network (graph)** where:\\\n- **Each subreddit is a dot (node).**\\\n- **A line (edge) connects two dots if one subreddit links to another.**\n\nTo see how different communities are connected and which ones are the most linked or influential.\n\n-   **SOURCE_SUBREDDIT** is where the link starts (the subreddit that posted the link).\\\n-   **TARGET_SUBREDDIT** is where the link goes (the subreddit being linked to).\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(igraph)\n\nedges <- reddit_data[, c(\"SOURCE_SUBREDDIT\", \"TARGET_SUBREDDIT\")]\n\nreddit_graph <- graph_from_data_frame(edges, directed = TRUE)\n\nsummary(reddit_graph)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIGRAPH 9ce47d5 DN-- 54075 571927 -- \n+ attr: name (v/c)\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\nThis tells us: - The network consists of **54,075 subreddits**. - There are **571,927 hyperlinks** connecting them. - The graph is **directed**, meaning links have a source and a destination.\n\n# Finding the most refrenced subreddits (in-degree centrality)\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_influential <- sort(degree(reddit_graph, mode = \"in\"), decreasing = TRUE)[1:10]\ncat(\"Top 10 Most Linked Subreddits (In-Degree Centrality):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 10 Most Linked Subreddits (In-Degree Centrality):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(top_influential)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    askreddit          pics          iama todayilearned         funny \n        19293          9799          9752          8753          8731 \n    worldnews        videos          news      politics        gaming \n         7687          7567          5928          4860          4695 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n# Finding the most active subreddits (out-degree centrailty)\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_outbound <- sort(degree(reddit_graph, mode = \"out\"), decreasing = TRUE)[1:10]\ncat(\"Top 10 Subreddits That Link the Most (Out-Degree Centrality):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 10 Subreddits That Link the Most (Out-Degree Centrality):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(top_outbound)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  subredditdrama           bestof        titlegore   shitredditsays \n           22971            21170             9500             7338 \n        shitpost     circlebroke2       switcharoo shitamericanssay \n            6657             6037             5997             5482 \n           drama  shitstatistssay \n            5478             4240 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n# Creating a network of the most refrenced subreddits\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the top 50 most linked subreddits by in-degree\ntop_50 <- names(sort(degree(reddit_graph, mode = \"in\"), decreasing = TRUE))[1:50]\n\n# Create a subgraph with only those subreddits\nsubreddit_subgraph <- induced_subgraph(reddit_graph, vids = top_50)\n\n# Convert to tidygraph for visualization\nlibrary(ggraph)\nlibrary(tidygraph)\n\nset.seed(42)\nggraph(as_tbl_graph(subreddit_subgraph), layout = \"kk\") + \n  geom_edge_link(aes(alpha = 0.5), color = \"gray\") +\n  geom_node_point(size = 5, aes(color = degree(subreddit_subgraph, mode = \"in\"))) +\n  geom_node_text(aes(label = name), repel = TRUE, size = 4) +\n  theme_void() +\n  ggtitle(\"Top 50 Most Linked Subreddits\")\n```\n\n::: {.cell-output-display}\n![](Assignment_2_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "Assignment_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}